### ISSUE TITLE
Button for sliding menu on mobile is invisible

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bitcoindevkit.org-old#14]
Making it unclear that the sections "Roadmap", "Blog", and "Github" exist if you come to the website from mobile.

**Comment by thunderbiscuit** [comment]
Found the problem: a typo in the class declaration of the icon. Should read `class="fa fa-bars"`, instead is `class="fas fa-bars"`.

But even from there you'd need the font-awesome imported. I see that there is indeed a directory `fa_` in the static folder, but it's not the typical font-awesome setup. I'm not sure if it's used somewhere else @notmandatory? It's not imported by the `index.html` template for by the `styles.css` or `page-styles.css` files. 

There might be something I don't know about how the font-awesome icons are used in this setup? Otherwise, I can just add the necessary font-awesome files and import it in index.html, and it'll work like a charm. Let me know if you have more insights into this!

**Comment by notmandatory** [comment]
I suspect you're right that the correct font-awesome files just need to be added and imported. I did a pretty quick hack and slash to get the original site up using style files copied from the btcpayserver site. If you can put in a PR to use the correct font-awesome files I'll test it out too just to confirm.

**Comment by thunderbiscuit** [comment]
You got it. I'll have something ready in a few minutes.
