### ISSUE TITLE
Need error handling for Github API rate limit

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bitcoindevkit.org-old#15]
Developing locally here and the site won't build because the IP I use is being throttled by Github (unautenticated queries are maxed at 60 per hour [as per this page](https://developer.github.com/v3/#rate-limiting). I assume my VPN has a lot of traffic with Github, and this type of thing will happen to other people who use VPNs a lot.

I haven't looked at how to handle that sort of error in Tera yet.

**Comment by notmandatory** [comment]
This is probably only an issue for testing on your locahost zola server. When the site builds on github it shouldn't be rate limited, or at least it will only build there when we merge a PR, so shouldn't pull from the API often enough to cause a problem.

**Comment by thunderbiscuit** [comment]
Yeah good point haha. Won't get build _that_ often.
