### ISSUE TITLE
The sidebar and content in docs are not mobile-friendly

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bitcoindevkit.org-old#2]
Somewhere in there as screen size decreases the sidebar and the content should be on top of each other (probably at the exact point where the sidebar becomes collapsible through the burger icon).

**Comment by thunderbiscuit** [comment]
@notmandatory you can have a look at how I implemented that on [learn-bitcoin-testnet](https://thunderbiscuit.github.io/learn-bitcoin-testnet/overview/node/) and see if that would be something you'd be interested in (I could port/massage the idea in here probably fairly easily).

The only thing is that in our case for bitcoindevkit.org we have a header and a footer, and the docs fit _inside_ of that. 

Actually testing for this made me realize that right now the site landing page is not mobile friendly, as the links in the header disappear on mobile. They're hidden in a sliding menu coming from the right but the button to trigger it doesn't have an icon and is therefore not visible (even though you can still click it).

Opened a new issue for it, as this, as that is independent of the "mobile-friendliness" of the docs.

**Comment by notmandatory** [comment]
@thunderbiscuit yes your learn-bitcoin-testnet site looks great on how it handles the side bar on mobile with the hamburger at list at the top. If you can adapt the same thing it will be a good step on the road to making the bdk site mobile friendly.

**Comment by thunderbiscuit** [comment]
This has now been fixed.
